#!/bin/bash
#Author: Josh McSavaney ( mcsaucy@csh.rit.edu )
#This will produce a full memory dump from the BetaBrite display.
#Check the documentation for help interpreting this.
#Seriously, it shouldn't be that hard to find. It's a little bit
#dodgy, but you should be fine. You look like a smart kid.
echo -e "\x00\x00\x00\x00\x00\x01Z00\x02F%\04" > /dev/ttyUSB0
