#!/bin/bash
#Author: Josh McSavaney ( mcsaucy@csh.rit.edu )
#A simple priority message script useful primarily for testing
echo -e "\x00\x00\x00\x00\x00\x01Z00\x02A0\x1B n6This is a priority message\x04" > /dev/ttyUSB0
